export const PRODUTO_LISTA_REQUEST =  'PRODUTO_LISTA_REQUEST'
export const PRODUTO_LISTA_SUCESS =  'PRODUTO_LISTA_SUCESS'
export const PRODUTO_LISTA_ERROR =  'PRODUTO_LISTA_ERROR'

export const PRODUTO_DETALHES_REQUEST =  'PRODUTO_DETALHES_REQUEST'
export const PRODUTO_DETALHES_SUCESS =  'PRODUTO_DETALHES_SUCESS'
export const PRODUTO_DETALHES_ERROR =  'PRODUTO_DETALHES_ERROR'
export const PRODUTO_DETALHES_RESET =  'PRODUTO_DETALHES_RESET'



export const PRODUTO_CREATE_REQUEST = 'PRODUTO_CREATE_REQUEST'
export const PRODUTO_CREATE_SUCCESS = 'PRODUTO_CREATE_SUCCESS'
export const PRODUTO_CREATE_ERROR = 'PRODUTO_CREATE_ERROR'
export const PRODUTO_CREATE_RESET = 'PRODUTO_CREATE_RESET'

export const PRODUTO_UPDATE_REQUEST = 'PRODUTO_UPDATE_REQUEST'
export const PRODUTO_UPDATE_SUCCESS = 'PRODUTO_UPDATE_SUCCESS'
export const PRODUTO_UPDATE_ERROR = 'PRODUTO_UPDATE_ERROR'
export const PRODUTO_UPDATE_RESET = 'PRODUTO_UPDATE_RESET'

export const PRODUTO_ADMIN_LISTA_REQUEST =  'PRODUTO_LISTA_REQUEST'
export const PRODUTO_ADMIN_LISTA_SUCCESS =  'PRODUTO_LISTA_SUCCESS'
export const PRODUTO_ADMIN_LISTA_ERROR =  'PRODUTO_LISTA_ERROR'

export const PRODUTO_DELETE_REQUEST = 'PRODUTO_DELETE_REQUEST'
export const PRODUTO_DELETE_SUCCESS = 'PRODUTO_DELETE_SUCCESS'
export const PRODUTO_DELETE_ERROR = 'PRODUTO_DELETE_ERROR'
export const PRODUTO_DELETE_RESET = 'PRODUTO_DELETE_RESET'


